### ISSUE TITLE
python refactor tracking issue

### ISSUE THREAD

**Issue by NOBLES5E** [BaguaSys/bagua#49]
- [x] bucketing
  - [x] bucketing function  
    - input: `List[BaguaTensor]`
    - output: `BaguaBucket`
  - [x] Bucket class  
    - underlying storage 
    - list of tensors
  - [x] get from and push to autotune(hyperparameter) server
- [x] register backward hook function
  - [x] register_backward_hook_for_all_parameters(model, callback: lambda)
- [x] algorithm classes
- [ ] optimizer
  - [ ] optimizer sharding function
    - input: original optimizer, List[BaguaBucket]
    - output: List[optimizer] 
- [ ] algorithms
  - [x] gradient allreduce
  - [x] 1bit adam
  - [x] lower precision gradient
  - [x] decentralized
  - [ ] low precision decentralized
  - [ ] async allreduce
  - [ ] sharded async

Test script https://github.com/BaguaSys/examples/tree/main/benchmark
